sudo: false
language: node_js
node_js:
- '4'
before_script:
- npm install -g bower grunt-cli
- bower install
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/realgt/seminary.git
  - secure: FbGTf4GzYje4TjSjpDCl2l1mqRNnFP5oeH55mUVpI/HA1OUFX4MmoRtu0flk6y5A5A0BAILZ4pPLHCJDxtlJHSItoh7wnm2Rky06zyfyW5LXgwoIA4Pu7MZJ6bK8HK72x7WuHj9HJrtRq52qPYbPSByNwDjojflyg6pVTqiExOGOfDFbFycWucP1hJDqHn7ukG1/l18lvA9wo8MDBpXCVOyor/OWvLU6bxNBWTZuAHxiqkrtWA3HC/GU5KFuMv31ER1JY2bEOY+IuVvMES4QLrkCrv3fZyNfpELW0/AyTYvPOsij68HPgrF8ke7t6534b08SQMrmPn5By/ZLMKEiteakTdbinFOey6c5zxfGvygxD2kFpDZ835wfb+DdT8CBdwjhUIL6Nc1PLetXx9cMrHejYPZOET7exNdOWXr4of5qKgm3u0uWiT0+nBZNODbOhGjMLLH3mbCyKtRQVTuaLoMUSl9btlN10uWzzWZ1hM6Bp6702RF5NMSWUWHF0stvKU+5Jj/g2cSVtr+c3swdevy+rdzESqBN5LRFJen4sKGWozA/gfz82tztExA1pzi6gy8c9KgWbHTjENh13fYp7M7tTF4ux9LY8MpVcUXChJHU3CBvrRy+IdSRRW1Gj9OBp05rYZ9Eorihq2cbrsIBiube76zD7s/QT6ZYCgBA/F8=
