sudo: false
language: node_js
node_js:
- '4'
before_script:
- npm install -g bower grunt-cli
- bower install
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/realgt/seminary.git
  - secure: 67b4f34feb3f1dd9a9eeca70440c5a49a60908f4
